# set default profile to 'dev'
spring.profiles.active: dev

twitter-to-kafka-service:
  twitter-keywords:
    - Ukraine
    - Ucrania
    #- Java
    #- Microservices
    #- SpringBoot
    #- Kafka
    #- Elasticsearch
  welcome-message: initializing application ....
  enable-v2-tweets: true
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 3000
  #?tweet.fields=created_at&expansions=author_id
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: AAAAAAAAAAAAAAAAAAAAAMlGgAEAAAAAFcb49EzFPgzAwu9gUZitkjLy1kk%3DbXMqTNxeCCd1100sVE2ZMSo4rc7lnDqOgIlx6RQ204TGg69c70

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5